ci
Change-Id: I2d72e0acc4a13001bc42b31889a0b6d7495ecb4b

diff --git a/.github/workflows/Screenshots.yaml b/.github/workflows/Screenshots.yaml
--- a/.github/workflows/Screenshots.yaml
+++ b/.github/workflows/Screenshots.yaml
@@ -45,25 +45,29 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
-
-      - name: Record screenshot tests (Roborazzi)
-        id: screenshots-verify
-        run: | 
-          ./gradlew :feature:foryou:recordRoborazziDemoDebug
+#
+#      - name: Record screenshot tests (Roborazzi)
+#        id: screenshots-verify
+#        run: |
+#          ./gradlew :feature:foryou:recordRoborazziDemoDebug
 
       - name: Generate md5 hashes
         run: | 
           ls screenshots/
           find screenshots/ -type f -name "*.png" -exec md5sum {} + | awk '{print $1 > $2 ".md5"}' 
 
-      - name: Fail if md5 hashes changed
+#      - name: Fail if md5 hashes changed
+#        id: md5-check
+#        continue-on-error: true
+#        run: git diff --exit-code --quiet -- screenshots/ && exit 0 || exit 1
+
+      - name: Just fail
         id: md5-check
-        continue-on-error: true
-        run: git diff --exit-code --quiet -- screenshots/ && exit 0 || exit 1
+        run: exit 1
 
       - name: debug
         if: always()
-        run: echo ${{ steps.md5-check.outputs }}
+        run: echo ${{ steps.md5-check.outputs.exit_code }}
 
       - name: Run all local screenshot tests (Roborazzi) if failed
         if: ${{ steps.md5-check.outputs.exit_code != 0 }}
